print('+  >>> Adição')
print('-  >>> Subtração')
print('*  >>> Multiplicação')
print('/  >>> Divisão')
print('** >>> Potência')
print('// >>> Divisão Inteira')
print('%  >>> Resto da Divisão')
print()
print('Ordem de Precedência:')
print('1 - ()')
print('2 - **')
print('3 - * / // %')
print('4 - + -')
print()
print(5 + 3 * 2)
print(3 * 5 + 4 ** 2)
print(3 * (5 + 4) ** 2)
